/*
 * OpenAPI Tutorial
 *
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetHealthResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetHealthResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetHealthResponse
        //private GetHealthResponse instance;

        public GetHealthResponseTests()
        {
            // TODO uncomment below to create an instance of GetHealthResponse
            //instance = new GetHealthResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetHealthResponse
        /// </summary>
        [Fact]
        public void GetHealthResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetHealthResponse
            //Assert.IsType<GetHealthResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
