/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetHealthResponse,
    GetHealthResponseFromJSON,
    GetHealthResponseToJSON,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * サーバーの状態を返します。
     * サーバーの状態を返します
     */
    async openapitutorialControllerHealthCallRaw(): Promise<runtime.ApiResponse<GetHealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHealthResponseFromJSON(jsonValue));
    }

    /**
     * サーバーの状態を返します。
     * サーバーの状態を返します
     */
    async openapitutorialControllerHealthCall(): Promise<GetHealthResponse> {
        const response = await this.openapitutorialControllerHealthCallRaw();
        return await response.value();
    }

}
