/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * サーバーの状態のレスポンス
 * @export
 * @interface GetHealthResponse
 */
export interface GetHealthResponse {
    /**
     * 
     * @type {string}
     * @memberof GetHealthResponse
     */
    status: GetHealthResponseStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum GetHealthResponseStatusEnum {
    Ok = 'ok'
}

export function GetHealthResponseFromJSON(json: any): GetHealthResponse {
    return GetHealthResponseFromJSONTyped(json, false);
}

export function GetHealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealthResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function GetHealthResponseToJSON(value?: GetHealthResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


